# Copyright (c) 2023 Ecosoft Co., Ltd.

site_name: Openerp for SQP
copyright: Copyright &copy; 2023 Ecosoft Co., Ltd.
repo_url: https://github.com/ecosoft-odoo/sqp-docs  # Add edit on github link
edit_uri: edit/master/docs  # Point to master branch
theme: readthedocs
nav:  # Content organization
  - "[[Manufacturing]]":
    - "การผลิตของโรง Continuous"
markdown_extensions:
    - toc:  # For link for hearders, H1, H2, etc.
        permalink: "#"  
    - admonition   # For !!! Note box
plugins:
    - search
