name: Build Document Template
on:
  push:
    branches:
      - 15.0
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-python@v4
      #  with:
      #    python-version: 3.x
      #- uses: actions/cache@v2
      #  with:
      #    key: ${{ github.ref }}
      #    path: .cache
      #- uses: fregante/setup-git-user@v2
      #- run: git pull
      - run: pip install mkdocs-material
      #- run: pip install mike
      #- run: mike deploy 15.0 --push
