name: Build Document Template

on:
  push:
    branches:
      - 16.0

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name GitHub Actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git pull
      - run: pip install mike mkdocs-material
      - run: mike deploy 16.0 --push
