name: Test Build Document Template

on:
  pull_request:
    branches:
      - 16.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs build
