name: Test Build Document Template

on:
  pull_request:
    branches:
      - 15.0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: git branch
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs build
