name: Test Build Document Template

on:
  pull_request:
    branches:
      - 15.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install mkdocs 
      - run: mkdocs build
