name: Test Run Document Template

on:
  pull_request:
    branches:
      - 15.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs serve
